### ISSUE TITLE
Check for Livestream

### ISSUE THREAD

**Issue by jacobkossman** [Jman012/Wasserflug-tvOS#11]
When opening the app, when the stream is live, the button won't light up and be clickable until restarting my device. not sure if i'm impatient or what, but if it can check each time the app is opened regardless of cache or something, that would be ideal.

thanks for the app ❤️

**Comment by Jman012** [comment]
See if 1.2.2-2 in Test Flight helps, it should be available to test now. I changed it so that the button is always clickable, but changes icon when it detects live vs. not live.

**Comment by Jman012** [comment]
I think I know what's going on now actually. The app first hits the CDN endpoint for livestream to get the URL, and then polls that URL every 5 seconds to see if it's live or not. One problem is if the app has not been killed since the last stream, it'll be an outdated URL. 

On the 2022-09-08 stream ("The Computer I Would actually BUY") there was an issue where LTT accidentally was streaming at 25mbit instead of 7mbit, and it caused the FP livestream to continuously go live for about 5 seconds every 30 seconds. When I ran Wasserflug in the simulator in the middle of this, it would refresh every 5 seconds to see if the stream was live or not, but once they actually fixed the stream (I think by restarting the attempted stream), the livestream would no longer load until I killed and restarted the app.

So, I need to make a change to re-pull the CDN info every so often as well as checking the resulting URL. 

I don't want to spam the CDN endpoint (it generates tokens used for secure streaming. I don't know what the impact of mass generating those would be, so let's be safe). So I might just remove the livestream 5-second interval checking and the icon, and just do all of the work when you click the Livestream button instead.

**Comment by Jman012** [comment]
I pushed 1.2.2-3 a few days ago. Included in it is a new livestream screen. Clicking into that will pull the latest CDN information and then poll for livestream status. If offline, it'll show the offline banner and text. Otherwise, it'll show the livestream itself.

This will help for the future because if/when I implement sockets for chat, then I have a screen to add that to, and perhaps toggle between fullscreen livestream and a smaller window with chat on the side, a la Twitch's tvOS app.

I haven't been able to test much since I'm usually out during the WAN Show. I'll push this to the app store soon, but it's on Test Flight for now.

**Comment by Jman012** [comment]
This was fixed in 1.2.2. Closing this issue.
