### ISSUE TITLE
Video Duration for Multi-Video Posts

### ISSUE THREAD

**Issue by jacobkossman** [Jman012/Wasserflug-tvOS#20]
LTT has started uploading FP exclusives with two videos: captioned / uncaptioned. When on the grid view, it seems to add all the lengths up so if the video is 30 mins, with 2 versions, it will count it as 1 hour. You can see this with the latest "meet the team".

I think the solution here (from a UI perspective) would be to change the type underneath the thumbnail from "Video" to "Multimedia" or "Videos". Then just not show a duration, then have individual durations under each video once you've clicked in.

**Comment by Jman012** [comment]
<img width="329" alt="Screenshot 2023-06-14 at 1 51 38 PM" src="https://github.com/Jman012/Wasserflug-tvOS/assets/419958/3f638355-8b61-42b1-8ced-3313926c56df">

You're correct! It looks like for multi-video uploads, the website doesn't show a duration. The duration I use comes from the blog post document metadata, which appears to be summing the total duration of all video attachments, not just the main video attachment.

I can remove the duration label for multi-video posts, since the metadata can't be trusted for display purposes, and the attachment-specific metadata isn't available in that part of the UI.

**Comment by Jman012** [comment]
Fixed in 1.3.0-16. Uploaded to TestFlight. Closing, but please re-open if you see any issues! Thanks for bringing this to my attention :)
