### ISSUE TITLE
Allow Player timeline scrubbing

### ISSUE THREAD

**Issue by CDeLeon94** [Jman012/Wasserflug-tvOS#21]
On long videos (like WAN) it’s a relatively slow process to fastforward significantly into a video. I believe this is a feature native to the TVos playback controls you seem to be using already.

**Comment by CDeLeon94** [comment]
Um, well actually it seems to scrub when paused only. (tvOS 17 beta) idk if this was normal behavior before. 

If scrubbing from the “playing state” is possible that’d  e great.

**Comment by Jman012** [comment]
I haven't used the tvOS 17 Beta yet, but I'm using the new player that was introduced in tvOS 16. 

Which Apple TV remote are you using? The older black one with the trackpad, or the newer aluminum one with the circle? When you pause the video with either remote, you should be able to scrub very quickly around. On the older remote, you can swipe left and right when paused and it should scrub quite quickly. On the newer remote, Apple changed things a bit and you can use circular motions to scrub around. For example, here's a quick guide: https://www.macrumors.com/how-to/scrub-through-video-new-siri-remote-2nd-gen/

Otherwise, while playing the left/right click will only skip 10 seconds at a time.

Did the tvOS 17 Beta change this dramatically? If so I can take a look into it.

**Comment by CDeLeon94** [comment]
New remote with the circle, the swiping left/right gesture works when paused. I think it’s just unexpected that I’d need to pause bc the youtube controls doesn’t require you to be paused to scrub, which is the app I’m on most. Looking around at Plex, AppleTV, and Infuse it seems like YT is the odd one out. Sent from my iPhoneOn Jul 22, 2023, at 3:12 PM, James Linnell ***@***.***> wrote:﻿
I haven't used the tvOS 17 Beta yet, but I'm using the new player that was introduced in tvOS 16.
Which Apple TV remote are you using? The older black one with the trackpad, or the newer aluminum one with the circle? When you pause the video with either remote, you should be able to scrub very quickly around. On the older remote, you can swipe left and right when paused and it should scrub quite quickly. On the newer remote, Apple changed things a bit and you can use circular motions to scrub around. For example, here's a quick guide: https://www.macrumors.com/how-to/scrub-through-video-new-siri-remote-2nd-gen/
Otherwise, while playing the left/right click will only skip 10 seconds at a time.
Did the tvOS 17 Beta change this dramatically? If so I can take a look into it.

**Comment by Jman012** [comment]
Yep, that would be correct. Youtube ditches the entire built-in interface and strays in the UX quite a bit! I honestly don't like that Youtube will scrub without pause, since I accidentally lose my place a lot haha. 

It sounds like nothing needs to be changed here. I'd rather stick to the default Apple TV experience than try to fiddle with things and break the norm from other apps (aside from Youtube). But feel free to re-open this or make other issues for other suggestions!
