### ISSUE TITLE
Unable to select 4K

### ISSUE THREAD

**Issue by sollie** [Jman012/Wasserflug-tvOS#7]
Hi.

The 4K option does not exist in my list of available resolutions.

I'm on an Apple TV a1842, I have a valid LTT Supporter Plus sub, I can stream in 4K from the official mobile app. I can also stream 4k from any other app on my Apple TV.

**Comment by Jman012** [comment]
4K screens: 3480 x 2160
LTT 4K videos: 4320 x 2160 (2:1 aspect ratio, credit to a screencap from https://www.floatplane.com/post/ShWQXkpWic)

Recent commit attempting to fix/improve this area of Wasserflug: 8b52c9bca95963f4104254b6e635d9494f0fe6a4

> Filter out resolutions larger than the device's screen resolution. LTT's videos at the stated 1080p are actually 2160x1080 instead of 1920x1080, like most television screens are. With a strict comparison, LTT 1080p videos would be filtered out on 1080p televisions. Thus, add 15% to the screen size to account for this. This will allow for actually getting 1080p on 1080p screens, with only a little bit of downsampling. But, it wouldn't make sense to show 4k on a 1080p screen. Waste of bandwidth, and the hardware may not like the massive downsampling.

1920 * 1.15 = 2208 which is greater than 2160, which is why 1080p videos show.

3480 * 1.15 = 4002 which is less than 4320, which is why 4K videos do not show.

I will switch this from width-based to height-based (and maybe keep the 15% tolerance) in order to fix the issue, since 15% at the 4K scale is not enough.

**Comment by ptirth** [comment]
Can confirm the same. On 4K plan but selection only possible till 1080P.

**Comment by Jman012** [comment]
This should be fixed in `1.2.1 (1)` once it becomes public on the Test Flight (should be within the next 48 hours).

**Comment by Jman012** [comment]
Version 1.2.1 has gone out to the App Store for review and publication.

**Comment by Jman012** [comment]
This has been fixed. Closing.
